### ISSUE TITLE
~/.boto

### ISSUE THREAD

**Issue by hschoenburg** [thelastmile/lms-backend#4]
Hey guys,

Hans from the last mile here. I know Wes said the app isn't ready yet, but i can't help myself! So I started poking around and encountered an error during the setup phase. Trying to visit the admin page threw a 'No AuthHandler Found' error. Adding a ~/.boto file with bogus credentials seemed to have fixed the problem for now but you might want to add something about this in the setup instructions.

Ah and I see all the css is on S3... ok, just playing around here.

**Comment by BenHavilland** [comment]
Hi Hans - I've added a local_settings example file and updated the instructions in the README to include usage of the local_settings.  It resolves the 'No AuthHandler Found' error as well as allowing hosting of static files locally when in dev.  Cheers

**Comment by BenHavilland** [comment]
Please let me know if you are able to get it deployed now - thanks!
